-- Initial Schema Migration: Users, Audit Context, Risk Flags, Ledger Entries

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_context (
    contract_id VARCHAR(255) PRIMARY KEY,
    contract_text TEXT,
    owner_id VARCHAR(255),
    state VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS risk_flag (
    flag_id VARCHAR(255) PRIMARY KEY,
    level VARCHAR(50),
    reason TEXT,
    quoted_span TEXT,
    decision VARCHAR(50),
    audit_id VARCHAR(255),
    CONSTRAINT fk_risk_flag_audit FOREIGN KEY (audit_id) REFERENCES audit_context (contract_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ledger_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_id VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    level VARCHAR(50),
    reason VARCHAR(2000),
    quoted_span VARCHAR(4000),
    timestamp TIMESTAMP WITH TIME ZONE
);
